Add storybook
akrolicki/react-boilerplate pull request #2
Opened 2023-02-08 10:17 UTC by arek-widelab

2023-02-08 10:22 UTC, akrolicki requested changes
jeszcze rozważyłbym zmianę nazwy logic na shared albo common da nam to przesztrzeń na wrzucenie czegoś co może nie być logiką - sam nie wiem czy to może mieć miejsce? 🤔 

ale na pewno zrezygnowałbym z tego dodatkowego folderu add w środku

2023-02-08 13:59 UTC, arek-widelab commented
traktuję, że to co w logic musi być logiką.
Co nie wyklucza, że może być wspólna.
Shared/common brzmi jak zbiornik na wszystko a nie wiem czy wszystko potrzebujemy albo czy logic i shared (na np. wspólne interfejsy) nie może być osobnym bytem od logic?

2023-02-09 09:04 UTC, akrolicki commented
> traktuję, że to co w logic musi być logiką. Co nie wyklucza, że może być wspólna. Shared/common brzmi jak zbiornik na wszystko a nie wiem czy wszystko potrzebujemy albo czy logic i shared (na np. wspólne interfejsy) nie może być osobnym bytem od logic?

miejsce na interfejsy trzymałbym osobno więc to co piszesz ma sens :)

2023-02-09 09:05 UTC, akrolicki approved these changes

2023-02-09 09:05 UTC, merged